DatingService/Controllers/ChatController.cs
using DatingService.Domain.Auth;
using DatingService.Infrastructure.ViewModels;
using DatingService.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DatingService.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private const int PageSize = 4;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IChatService _chatService;
        private readonly IMessageService _messageService;

        public ChatController(
            UserManager<ApplicationUser> userManager,
            IChatService chatService,
            IMessageService messageService)
        {
            _userManager = userManager;
            _chatService = chatService;
            _messageService = messageService;
        }

        public async Task<IActionResult> ListAsync(Guid? id, int page = 1, string filter = null)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var chats = filter == null ? _chatService.GetAll(user) : _chatService.GetAll(user).ToList().Where(c => c.Users.Any(u => u != user && u.FullName.ToUpper().Contains(filter.ToUpper())));

            var count = chats.Count();
            var items = chats.Skip((page - 1) * PageSize).Take(PageSize).ToList();

            var pageViewModel = new PageViewModel(count, page, PageSize);

            var selectChat = items.Count == 0 ? null : id == null ? items.First() : chats.Where(c => c.Id == id).First();
            if (selectChat != null)
            {
                selectChat.DateUpdated = DateTime.Now;
                _chatService.Update(selectChat);
            }

            var viewModel = new ChatListViewModel()
            {
                Chats = items,
                PageViewModel = pageViewModel,
                SelectChat = selectChat,
                Filter = filter
            };

            return View(viewModel);
        }

        public IActionResult Details(Guid id)
        {
            var chat = _chatService.Get(id);
            if (chat == null)
            {
                return NotFound();
            }
            chat.Messages = _messageService.GetAll(chat).ToList();
            return View(chat);
        }
    }
}

DatingService/Controllers/FriendController.cs
using DatingService.Domain.Auth;
using DatingService.Domain.Entities;
using DatingService.Domain.Enums;
using DatingService.Infrastructure.ViewModels;
using DatingService.Service.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatingService.Controllers
{
    public class FriendController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRequestService _requestService;
        private readonly IChatService _chatService;
        private readonly IMessageService _messageService;
        private readonly IPostService _postService;
        private readonly IReportService _reportService;
        private readonly IReportCategoryService _reportCategoryService;
        private int pageSize = 10;

        public FriendController(UserManager<ApplicationUser> userManager,
                                IRequestService requestService,
                                IChatService chatService,
                                IMessageService messageService,
                                IPostService postService,
                                IReportService reportService,
                                 IReportCategoryService reportCategoryService)
        {
            _userManager = userManager;
            _requestService = requestService;
            _chatService = chatService;
            _messageService = messageService;
            _postService = postService;
            _reportService = reportService;
            _reportCategoryService = reportCategoryService;
        }

        public async Task<IActionResult> ListAsync(int page = 1)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var friends = _requestService.GetUserFriends(user).ToList();
            var count = friends.Count();
            var items = friends.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            List<Request> requests = new List<Request>();
            foreach (var friend in items)
            {
                requests.Add(_requestService.Get(user, friend));
            }
            var friendsViewModel = new FriendsViewModel()
            {
                Friends = items,
                Requests = requests,
                PageViewModel = pageViewModel,
            };
            return View(friendsViewModel);
        }

        public async Task<IActionResult> DetailsAsync(Guid id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }
            user.Posts = await _postService.GetAll(user).ToListAsync();
            return View(user);
        }

        public async Task<IActionResult> UsersAsync(int page = 1)
        {

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var users = _userManager.Users.Where(u => u != user).Include(u => u.Gender).ToList();
            var count = users.Count();
            var items = users.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var pageViewModel = new PageViewModel(count, page, pageSize);
            var usersViewModel = new UsersViewModel()
            {
                Users = items,
                Friends = _requestService.GetUserFriends(user).ToList(),
                PageViewModel = pageViewModel,
            };
            return View(usersViewModel);
        }

        public async Task<IActionResult> RequestsAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var requestsViewModel = new RequestViewModel()
            {
                OutgoingRequests = _requestService.GetAllOutgoingByUser(user),
                IncomingRequests = _requestService.GetAllIncomingByUser(user),
            };
            return View(requestsViewModel);
        }

        public async Task<IActionResult> AddToFriendsAsync(string userId)
        {
            if (!_requestService.IsRequestExistence(await _userManager.GetUserAsync(HttpContext.User), await _userManager.FindByIdAsync(userId)))
            {
                var request = new Request()
                {
                    ReceiverId = Guid.Parse(userId),
                    Sender = await _userManager.GetUserAsync(HttpContext.User),
                };
                _requestService.Update(request);
            }
            return RedirectToAction("Users");
        }

        public IActionResult ChangeRequestStatus(Guid requestId, bool confirmed)
        {
            var request = _requestService.Get(requestId);
            if (confirmed == true)
            {
                request.RequestStatus = RequestStatus.Accepted;
                _requestService.Update(request);
            }
            else
            {
                _requestService.Remove(request.Id);
            }
            return RedirectToAction("Requests");
        }

        public async Task<IActionResult> ChatAsync(string userId)
        {
            var user1 = await _userManager.GetUserAsync(HttpContext.User);
            var user2 = _userManager.FindByIdAsync(userId).Result;
            var chat = _chatService.Get(user1, user2);
            if (chat == default)
            {
                chat = new Chat()
                {
                    Users = new List<ApplicationUser> { user1, user2 }
                };
                _chatService.Update(chat);
            }
            chat.Messages = _messageService.GetAll(chat).ToList();
            return View(chat);
        }

        [HttpGet]
        public IActionResult CreateReport(Guid userId)
        {
            var report = new Report
            {
                ReceiverId = userId
            };

            ViewBag.ReportCategories = new SelectList(_reportCategoryService.GetAll(), "Id", "Name");

            return View(report);
        }
        [HttpPost]
        public async Task<IActionResult> CreateReport(Report report)
        {
            //var post = _postService.Get(id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            report.SenderId = user.Id;
            //var report = _reportService.Get(user, post);

            //if (report == null)
            //{
            //    report = new Report
            //    {
            //        Post = post,
            //        User = user,
            //    };
            //}
            //report.CategoryId = reportCategoryId;

            _reportService.Add(report);
            return RedirectToAction("List");
        }
    }
}

DatingService/Controllers/UserRelationshipController.cs
using DatingService.Domain.Auth;
using DatingService.Domain.Entities;
using DatingService.Domain.Enums;
using DatingService.Infrastructure.ViewModels;
using DatingService.Service.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatingService.Controllers
{
    public class UserRelationshipController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRequestService _requestService;
        private readonly IChatService _chatService;
        private readonly IMessageService _messageService;
        private int pageSize = 10;

        public UserRelationshipController(UserManager<ApplicationUser> userManager, IRequestService requestService, IChatService chatService, IMessageService messageService)
        {
            _userManager = userManager;
            _requestService = requestService;
            _chatService = chatService;
            _messageService = messageService;
        }

        public async Task<IActionResult> FriendsAsync(int page = 1)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var friends = _requestService.GetUserFriends(user).ToList();
            var count = friends.Count();
            var items = friends.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            List<Request> requests = new List<Request>();
            foreach (var friend in items)
            {
                requests.Add(_requestService.Get(user, friend));
            }
            var friendsViewModel = new FriendsViewModel()
            {
                Friends = items,
                Requests = requests,
                PageViewModel = pageViewModel,
            };
            return View(friendsViewModel);
        }

        public async Task<IActionResult> UsersAsync(int page = 1)
        {

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var users = _userManager.Users.Where(u => u != user).Include(u => u.Gender).ToList();
            var count = users.Count();
            var items = users.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            var usersViewModel = new UsersViewModel()
            {
                Users = items,
                Friends = _requestService.GetUserFriends(user).ToList(),
                PageViewModel = pageViewModel,
            };
            return View(usersViewModel);
        }

        public async Task<IActionResult> RequestsAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var requestsViewModel = new RequestViewModel()
            {
                OutgoingRequests = _requestService.GetAllOutgoingByUser(user),
                IncomingRequests = _requestService.GetAllIncomingByUser(user),
            };
            return View(requestsViewModel);
        }

        public async Task<IActionResult> AddToFriendsAsync(string userId)
        {
            if (!_requestService.IsRequestExistence(await _userManager.GetUserAsync(HttpContext.User), await _userManager.FindByIdAsync(userId)))
            {
                var request = new Request()
                {
                    ReceiverId = Guid.Parse(userId),
                    Sender = await _userManager.GetUserAsync(HttpContext.User),
                };
                _requestService.Update(request);
            }
            return RedirectToAction("Users");
        }

        public IActionResult ChangeRequestStatus(Guid requestId, bool confirmed)
        {
            var request = _requestService.Get(requestId);
            if (confirmed == true)
            {
                request.RequestStatus = RequestStatus.Accepted;
                _requestService.Update(request);
            }
            else
            {
                _requestService.Remove(request.Id);
            }
            return RedirectToAction("Requests");
        }

        public async Task<IActionResult> ChatAsync(string userId)
        {
            var user1 = await _userManager.GetUserAsync(HttpContext.User);
            var user2 = _userManager.FindByIdAsync(userId).Result;
            var chat = _chatService.Get(user1, user2);
            if (chat == default)
            {
                chat = new Chat()
                {
                    Users = new List<ApplicationUser> { user1, user2 }
                };
                _chatService.Update(chat);
            }
            chat.Messages = _messageService.GetAll(chat).ToList();
            return View(chat);
        }
    }
}

DatingService/Views/UserRelationship/Chat.cshtml
@model Chat
@inject UserManager<ApplicationUser> userManager

<div id="comments">
    @if (Model.Messages != null)
    {
        @foreach (var message in Model.Messages)
        {
            <div class="box @(message.UserId == userManager.FindByNameAsync(User.Identity.Name).Result.Id ? "box_right" : "box_left")">
                <p class="card-text">@userManager.GetUserNameAsync(userManager.FindByIdAsync(message.UserId.ToString()).Result).Result</p>
                <div class="card text-white bg-info mb-3 w-100">
                    <div class="card-body">
                        <h5 class="card-title">@message.Content</h5>
                        <p class="card-text text-right"><small class="text">message.DateCreated</small></p>
                    </div>
                </div>
            </div>
        }
    }
</div>
<form>
    <input type="hidden" asp-for="@Model.Id" class="form-control" id="chatId" />
    <div class="form-group">
        <textarea class="form-control" placeholder="Комментарий" rows="5" id="content"></textarea>
    </div>
    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Отправить" id="send" />
    </div>
</form>
<style>
    #comments {
        text-align: left;
        margin: 0 auto;
        margin-bottom: 25px;
        padding: 10px;
        background: #fff;
        height: 40rem;
        width: 100%;
        overflow: auto;
    }
</style>
<link rel="stylesheet" href="~/css/message.css" />
<style>
    .box {
        /*min-height: 200px;*/
        width: 50%;
        padding: .8em;
    }

    .box_left {
        margin: 0 auto 0 0;
    }

    .box_center {
        margin: 0 auto;
    }

    .box_right {
        margin: 0 0 0 auto;
    }

    .box + .box {
        margin-top: 0px;
    }
</style>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    const currentUserName = '@User.Identity.Name';
    var curPos = $(document).scrollTop();
    var height = $("#comments").height();
    var scrollTime = (height - curPos) / 1.73;
    //$("#comments").animate({ "scrollTop": height }, "slow");
    //$("#comments").animate({
    //    scrollTop: ($("#comments").offset().top + $("#comments").height())
    //}, 500);
  //  $("#comments").scrollTop(100)
    var objDiv = document.getElementById("comments");
    objDiv.scrollTop = objDiv.scrollHeight;
</script>
<script src="~/lib/microsoft-signalr/signalr.min.js"></script>
<script src="~/js/sendMessages.js"></script>

DatingService/Views/UserRelationship/Friends.cshtml
@addTagHelper *, DatingService
@model FriendsViewModel

<head>
    <title>@ViewData["Title"] - Пользователи</title>
</head>
<body>
    <div>
        Друзей онлайн : <span id="onlineUsersCount"></span>
    </div>
    <div>
        <page-link page-model="Model.PageViewModel" page-action="Friends"></page-link>
    </div>
    <table class="table" id="userList">
        <thead>
        </thead>
        <tbody>
            @foreach (var item in Model.Friends)
            {
                var path = item.Avatar?.Path;
                @if (path == null)
                {
                    path = item.Gender?.Name == "Woman" ? "no-profile-image-f.svg" : "no-profile-image-m.svg";
                }
                <tr>
                    <td><img class="rounded-circle" style="height:5rem; width:5rem" src="~/Files/Images/Avatars/@path" data-holder-rendered="true"></td>
                    <td>Ofline</td>
                    <td>@item.Email</td>
                    <td>
                        <a type="button" class="btn btn-primary" asp-controller="UserRelationship" asp-action="Chat" asp-route-userId="@item.Id">Написать сообщение</a>
                        <a type="button" class="btn btn-primary" asp-controller="UserRelationship" asp-action="ChangeRequestStatus" asp-route-requestId="@Model.Requests.ElementAt(Model.Friends.IndexOf(item)).Id" asp-route-confirmed="@false">Удалить из друзей</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</body>
@*<style>
        .btn {
            background-color: transparent; /* Blue background */
            border: none; /* Remove borders */
            color: royalblue; /* White text */
            padding: 12px 16px; /* Some padding */
            font-size: 16px; /* Set a font size */
            cursor: pointer; /* Mouse pointer on hover */
        }
            /* Darker background on mouse-over */
            .btn:hover {
                background-color: transparent;
                color: blue;
            }
    </style>*@