DatingService/Controllers/ChatController.cs
using DatingService.Domain.Auth;
using DatingService.Infrastructure.ViewModels;
using DatingService.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DatingService.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private const int PageSize = 4;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IChatService _chatService;
        private readonly IMessageService _messageService;

        public ChatController(
            UserManager<ApplicationUser> userManager,
            IChatService chatService,
            IMessageService messageService)
        {
            _userManager = userManager;
            _chatService = chatService;
            _messageService = messageService;
        }

        public async Task<IActionResult> ListAsync(Guid? id, int page = 1, string filter = null)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var chats = filter == null ? _chatService.GetAll(user) : _chatService.GetAll(user).ToList().Where(c => c.Users.Any(u => u != user && u.FullName.ToUpper().Contains(filter.ToUpper())));

            var count = chats.Count();
            var items = chats.Skip((page - 1) * PageSize).Take(PageSize).ToList();

            var pageViewModel = new PageViewModel(count, page, PageSize);

            var selectChat = items.Count == 0 ? null : id == null ? items.First() : chats.Where(c => c.Id == id).First();
            if (selectChat != null)
            {
                selectChat.DateUpdated = DateTime.Now;
                _chatService.Update(selectChat);
            }

            var viewModel = new ChatListViewModel()
            {
                Chats = items,
                PageViewModel = pageViewModel,
                SelectChat = selectChat,
                Filter = filter
            };

            return View(viewModel);
        }

        public IActionResult Details(Guid id)
        {
            var chat = _chatService.Get(id);
            if (chat == null)
            {
                return NotFound();
            }
            chat.Messages = _messageService.GetAll(chat).ToList();
            return View(chat);
        }
    }
}

DatingService/Controllers/MatchController.cs
using DatingService.Domain.Auth;
using DatingService.Domain.Entities;
using DatingService.Domain.Enums;
using DatingService.Infrastructure.ViewModels;
using DatingService.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatingService.Controllers
{
    [Authorize]
    public class MatchController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRequestService _requestService;
        private readonly IChatService _chatService;
        private readonly IMessageService _messageService;
        private readonly IPostService _postService;
        private readonly IReportService _reportService;
        private readonly IReportCategoryService _reportCategoryService;
        private readonly IGenderService _genderService;
        private int PageSize = 4;

        public MatchController(UserManager<ApplicationUser> userManager,
                                IRequestService requestService,
                                IChatService chatService,
                                IMessageService messageService,
                                IPostService postService,
                                IReportService reportService,
                                 IReportCategoryService reportCategoryService,
                                 IGenderService genderService)
        {
            _userManager = userManager;
            _requestService = requestService;
            _chatService = chatService;
            _messageService = messageService;
            _postService = postService;
            _reportService = reportService;
            _reportCategoryService = reportCategoryService;
            _genderService = genderService;
        }

        public async Task<IActionResult> ListAsync(int page = 1, string filter = null)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return NotFound();
            }

            var friends = _requestService.GetUserFriends(user).ToList();

            if (filter != null)
            {
                friends = friends.Where(p => p.FullName.ToUpper().Contains(filter.ToUpper())).ToList();
            }

            var count = friends.Count();
            var items = friends.Skip((page - 1) * PageSize).Take(PageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, PageSize);

            var friendsViewModel = new MatchListViewModel()
            {
                Matches = items,
                PageViewModel = pageViewModel,
            };
            return View(friendsViewModel);
        }

        public async Task<IActionResult> DetailsAsync(Guid id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }

            if (user.GenderId != null)
            {
                user.Gender = _genderService.Get(user.GenderId.Value);
            }

            user.Posts = await _postService.GetAll(user).ToListAsync();
            return View(user);
        }

        public async Task<IActionResult> RequestsAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var requestsViewModel = new RequestViewModel()
            {
                OutgoingRequests = _requestService.GetAllOutgoingByUser(user),
                IncomingRequests = _requestService.GetAllIncomingByUser(user),
            };
            return View(requestsViewModel);
        }

        public async Task<IActionResult> RemoveMatch(string Id)
        {
            var firstUser = await _userManager.GetUserAsync(HttpContext.User);
            if (firstUser == null)
            {
                return NotFound();
            }

            var secondUser = await _userManager.FindByIdAsync(Id);
            if (secondUser == null)
            {
                return NotFound();
            }

            var request = _requestService.Get(firstUser, secondUser);
            if (request == null)
            {
                return NotFound();
            }

            _requestService.Remove(request.Id);
            return RedirectToAction("List");
        }

        public IActionResult ChangeRequest(Guid requestId, bool confirmed)
        {
            var request = _requestService.Get(requestId);
            if (confirmed == true)
            {
                request.RequestStatus = RequestStatus.Accepted;
                _requestService.Update(request);
            }
            else
            {
                _requestService.Remove(request.Id);
            }
            return RedirectToAction("Requests");
        }

        [HttpGet]
        public IActionResult CreateReport(Guid userId)
        {
            var report = new Report
            {
                ReceiverId = userId
            };

            ViewBag.ReportCategories = new SelectList(_reportCategoryService.GetAll(), "Id", "Name");

            return View(report);
        }

        [HttpPost]
        public async Task<IActionResult> CreateReport(Report report)
        {
            //var post = _postService.Get(id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            report.SenderId = user.Id;
            //var report = _reportService.Get(user, post);

            //if (report == null)
            //{
            //    report = new Report
            //    {
            //        Post = post,
            //        User = user,
            //    };
            //}
            //report.CategoryId = reportCategoryId;

            _reportService.Add(report);
            return RedirectToAction("List");
        }
    }
}

DatingService/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DatingService.Domain.Entities;
using DatingService.Persistence;
using DatingService.Service.Interfaces;
using Microsoft.AspNetCore.Identity;
using DatingService.Domain.Auth;
using Microsoft.AspNetCore.Http;
using DatingService.Domain.Options;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.Extensions.Options;
using DatingService.Infrastructure.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace DatingService.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private const int PageSize = 5;

        private readonly IOrderService _orderService;
        private readonly IPostService _postService;
        private readonly ICommentService _commentService;
        private readonly IImageService _imageService;
        private readonly PostOptions _postOptions;
        private readonly IFileService _fileService;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;

        public PostController(IPostService postService,
            ICommentService commentService,
            UserManager<ApplicationUser> userManager,
            IOptions<PostOptions> postOptions,
            IFileService fileService,
            IWebHostEnvironment environment,
            IImageService imageService,
            IOrderService orderService)
        {
            _postService = postService;
            _commentService = commentService;
            _userManager = userManager;
            _postOptions = postOptions.Value;
            _fileService = fileService;
            _environment = environment;
            _imageService = imageService;
            _orderService = orderService;
        }

        public async Task<IActionResult> ListAsync(int page = 1, string filter = null)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return NotFound();
            }

            var posts = _postService.GetAll(user);

            if (filter != null)
            {
                posts = posts.Where(p => p.Title.ToUpper().Contains(filter.ToUpper()));
            }

            var count = await posts.CountAsync();
            var items = await posts.Skip((page - 1) * PageSize).Take(PageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, PageSize);
            PostListViewModel viewModel = new PostListViewModel
            {
                Filter = filter,
                PageViewModel = pageViewModel,
                Posts = items
            };

            return View(viewModel);
        }

        public async Task<IActionResult> DetailsAsync(Guid id)
        {
            var post = _postService.Get(id);
            if (post == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return NotFound();
            }

            var comments = _commentService.GetAll(post).ToList();
            foreach (Comment comment in comments)
            {
                comment.User = await _userManager.FindByIdAsync(comment.UserId.ToString());
            }

            ViewBag.Comments = comments;
            return View(post);
        }

        public async Task<IActionResult> CreateAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return NotFound();
            }

            var postCount = _postService.GetAll(user).Count();
            if(postCount == user.PostCount)
            {
                return RedirectToAction("SetPostsCount", "Order");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostViewModel model, IFormFile file)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(user == null)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                var post = new Post
                {
                    Id = Guid.NewGuid(),
                    UserId = user.Id,
                    Title = model.Title,
                    Content = model.Content
                };

                if (file != null)
                {
                    var image = new Image();
                    var fileName = user.Id.ToString() + "-" + post.DateCreated.ToString("dd-MM-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                    var path = Path.Combine(_environment.WebRootPath, _postOptions.Path, fileName);
                    _fileService.Save(file, path);
                    image.Name = user.UserName;
                    image.Path = fileName;
                    image.PostId = post.Id;
                    post.Image = image;
                }

                _postService.Add(post);
                return RedirectToAction("List");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var post = _postService.Get(id);
            if (post == null)
            {
                return NotFound();
            }

            if (post.ImageId != null)
            {
                post.Image = _imageService.Get(post.Id);
            }

            var model = new PostViewModel
            {
                Id = post.Id,
                Title = post.Title,
                Content = post.Content,
                ImagePath = post.Image?.Path
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PostViewModel model, IFormFile file)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (ModelState.IsValid)
            {
                var post = _postService.Get(model.Id);
                if (post == null)
                {
                    return NotFound();
                }

                if (file != null)
                {
                    var image = post.ImageId == null ? new Image() : _imageService.Get(post.ImageId.Value);
                    var fileName = user.Id.ToString() + "-" + post.DateCreated.ToString("dd-MM-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                    var path = Path.Combine(_environment.WebRootPath, _postOptions.Path, fileName);
                    _fileService.Save(file, path);
                    image.Name = user.UserName;
                    image.Path = fileName;
                    image.PostId = post.Id;
                    post.Image = image;
                }

                post.Title = model.Title;
                post.Content = model.Content;
                post.DateUpdated = DateTime.Now;

                _postService.Update(post);
                return RedirectToAction("List");
            }

            return View(model);
        }

        public IActionResult Delete(Guid id)
        {
            var post = _postService.Get(id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var post = _postService.Get(id);
            if (post == null)
            {
                return NotFound();
            }

            _postService.Remove(id);

            return RedirectToAction("List");
        }

    }
}

DatingService/Views/Match/CreateReport.cshtml
@model Report

<div class="row justify-content-center align-items-start">
    <div class="col-md-4 shadow m-2 p-4">
        <form asp-action="CreateReport" method="post">
            <div class="form-group">
                <label asp-for="Category"></label>
                <select asp-for="ReportCategoryId" asp-items="ViewBag.ReportCategories"></select>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="ReceiverId" class="form-control" />
            </div>
            <div>
                <label asp-for="Content"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
    </div>
</div>

DatingService/Views/Match/Details.cshtml
@model ApplicationUser

@{
    ViewData["Title"] = "Requests";
}

@functions {
    public string GetAvatarPath(ApplicationUser user)
    {
        var path = user.AvatarPath;
        if (path == null)
        {
            path = user.Gender?.Name == "Man" ? "no-profile-image-m.svg" : "no-profile-image-f.svg";
        }
        return path;
    }
}

<div class="row align-items-start  m-2">
    <div class="col-md-6 text-center mr-4">
        <div class="card shadow mb-4 px-2 py-4">
            <img class="rounded-circle mx-auto card-img-top" style="min-height: 2rem; max-height: 10rem; min-width: 2rem; max-width: 10rem " src="~/Files/Images/Avatars/@GetAvatarPath(Model)" data-holder-rendered="true">
            <h2 class="text-dark">@Model.FullName</h2>
        </div>
        <h3 class="text-left">Info</h3>
        <div class="mb-4 text-left">
            <div class="card shadow mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-5">First Name</div>
                        <div class="col-sm-6 text-secondary">@Model.FirstName</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">Last Name</div>
                        <div class="col-sm-6 text-secondary">@Model.LastName</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-5">Date Of Birth</div>
                        <div class="col-sm-6 text-secondary">@Model.DateOfBirth.ToShortDateString()</div>
                    </div>
                    <hr>
                    @if (Model.Gender != null)
                    {
                        <div class="row">
                            <div class="col-sm-5">Gender</div>
                            <div class="col-sm-6 text-secondary">@Model.Gender.Name</div>
                        </div>
                    }
                    <hr>
                </div>
            </div>
            <h3 class="text-left">Contacts</h3>
            <div class="card shadow mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-5">Email</div>
                        <div class="col-sm-6 text-secondary">@Model.Email</div>
                    </div>
                    <hr>
                    @if (Model.PhoneNumber != null)
                    {
                        <div class="row">
                            <div class="col-sm-5">Phone Number</div>
                            <div class="col-sm-6 text-secondary">@Model.PhoneNumber</div>
                        </div>
                        <hr>
                    }
                </div>
            </div>
        </div>

    </div>

    <div class="col-md-5  px-4 py-2">
        <h2>Posts</h2>
        <div>
            @foreach (var item in Model.Posts)
            {
                var postPath = "";
                @if (item.Image?.Path != null)
                {
                    postPath = item.Image?.Path;
                }
                else
                {
                    postPath = "no-title-image.jpeg";
                }
                <div class="card shadow my-4">

                    <img src="~/Files/Images/Posts/@postPath" alt="@item.Title Image" class="card-img-top" style="">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                    </div>
                    <div class="card-footer text-right">
                        <a asp-area="" asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="card-link stretched-link" style="text-decoration: underline">Details</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<link rel="stylesheet" href="~/css/matchDeatails.css" />

DatingService/Views/Match/List.cshtml
@model MatchListViewModel

@inject UserManager<ApplicationUser> _userManager
@inject IChatService _chatService

@functions{
    public async Task<Guid> GetChatId(Guid userId)
    {
        var user1 = await _userManager.GetUserAsync(@User);
        var user2 = _userManager.FindByIdAsync(userId.ToString()).Result;
        var chat = _chatService.Get(user1, user2);
        if (chat == default)
        {
            chat = new Chat()
            {
                Users = new List<ApplicationUser> { user1, user2 }
            };
            _chatService.Update(chat);
        }
        return chat.Id;
    }
}

@{
    ViewData["Title"] = "Matches";
}

<h1 class="mb-4">@ViewData["Title"]</h1>

<div class="my-4">
    <form id="filterMatchesForm" method="get" class="d-flex">
        <div class="input-group h-100">
            <input type="text" asp-for="Filter" class="form-control" placeholder="Search">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
</div>

<div class="container">
    <div class="row">
        @foreach (var item in Model.Matches)
        {
            var path = item.AvatarPath;
            @if (path == null)
            {
                path = item.GenderId == Guid.Parse("b50075d8-0379-4b95-b0c2-50bba4509dab") ? "no-profile-image-f.svg" : "no-profile-image-m.svg";
            }

            <div class="col-12 col-sm-6 col-lg-3">
                <div class="single_advisor_profile wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                    <div class="advisor_thumb">
                        <img src="~/Files/Images/Avatars/@path" style="height: 16rem;" alt="">

                        <div class="social-info">
                            <a asp-controller="Match" asp-action="Details" asp-route-id="@item.Id">
                                <i class="fas fa-info" style="font-size: 1rem;"></i>
                            </a>
                            <a asp-controller="Chat" asp-action="Details" asp-route-id="@GetChatId(item.Id).Result">
                                <i class="fas fa-comments" style="font-size: 1rem;"></i>
                            </a>
                            <a asp-controller="Match" asp-action="RemoveMatch" asp-route-id="@item.Id" asp-route-confirmed="@false">
                                <i class="fas fa-trash" style="font-size: 1rem;"></i>
                            </a>
                            <a asp-controller="Match" asp-action="CreateReport" asp-route-userId="@item.Id">
                                <i class="fas fa-lock" style="font-size: 1rem;"></i>
                            </a>
                        </div>
                    </div>

                    <div class="single_advisor_details_info">
                        <p style="font-size: 1.5rem;">@item.FullName</p>
                        <p class="designation">@item.DateOfBirth.ToShortDateString()</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<page-link model="@Model.PageViewModel" action="List" action-filter="@(Model.Filter)"></page-link>

DatingService/Views/Match/Requests.cshtml
@model RequestViewModel

@{
    ViewData["Title"] = "Requests";
}

<h1 class="mb-4">@ViewData["Title"]</h1>

<div class="row align-items-start m-2">
    <div class="col-md-6 shadow px-4 py-2 mb-4 mr-4">
        <h2>Inbox</h2>

        <div class="p-2 m-1">
            @foreach (var item in Model.IncomingRequests)
            {
                var path = item.Sender.AvatarPath;
                @if (path == null)
                {
                    path = item.Sender.GenderId == Guid.Parse("b50075d8-0379-4b95-b0c2-50bba4509dab") ? "no-profile-image-f.svg" : "no-profile-image-m.svg";
                }
                <hr />
                <div class="row px-2 py-4 m-2 align-items-center justify-content-between">
                    <div class="p-1">
                        <img class="rounded-circle" style="height:4rem; width:4rem" src="~/Files/Images/Avatars/@path" data-holder-rendered="true">
                        <a asp-controller="Match" asp-action="Details" asp-route-id="@item.SenderId" class="m-0 align-self-center text-info" style="text-decoration: underline;">@item.Sender.FullName</a>
                    </div>

                    <div class="p-1">
                        <a type="button" class="btn btn-primary m-1" asp-controller="Match" asp-action="ChangeRequest" asp-route-requestId="@item.Id" asp-route-confirmed="@true">
                            <i class="fas fa-user-check"></i> Accept
                        </a>
                        <a type="button" class="btn btn-danger m-1" asp-controller="Match" asp-action="ChangeRequest" asp-route-requestId="@item.Id" asp-route-confirmed="@false">
                            <i class="fas fa-user-times"></i> Reject
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="col-md-4 shadow px-4 py-2">
        <h2>Sent</h2>

        <div class="p-2 m-1">
            @foreach (var item in Model.OutgoingRequests)
            {
                var path = item.Receiver.AvatarPath;
                @if (path == null)
                {
                    path = item.Receiver.GenderId == Guid.Parse("b50075d8-0379-4b95-b0c2-50bba4509dab") ? "no-profile-image-f.svg" : "no-profile-image-m.svg"; ;
                }
                <hr />
                <div class="row px-2 py-4 m-2 align-items-center justify-content-between">
                    <div class="p-1">
                        <img class="rounded-circle" style="height:4rem; width:4rem" src="~/Files/Images/Avatars/@path" data-holder-rendered="true">
                        <a asp-controller="Match" asp-action="Details" asp-route-id="@item.ReceiverId" class="m-0 align-self-center text-info" style="text-decoration: underline;">@item.Receiver.FullName</a>
                    </div>

                    <div class="p-1">
                        <a type="button" class="btn btn-danger" asp-controller="Match" asp-action="ChangeRequest" asp-route-requestId="@item.Id" asp-route-confirmed="@false">
                            <i class="fas fa-times"></i> Cancel
                        </a>
                    </div>
                </div>

            }
        </div>
    </div>
</div>